name: Trigger Watchtower Update

on:
  workflow_call:
    inputs:
      watchtower_base_url:
        description: 'Base URL of Watchtower (e.g. http://yourhost:8080)'
        required: true
        type: string
    secrets:
      bearer_token:
        required: true

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    env:
      WATCHTOWER_BASE_URL: ${{ inputs.watchtower_base_url }}
      BEARER_TOKEN: ${{ secrets.bearer_token }}

    steps:
      - name: Mask the token
        run: echo "::add-mask::$BEARER_TOKEN"

      - name: Trigger Watchtower Update
        run: |
          curl -X POST \
            -H "Authorization: Bearer $BEARER_TOKEN" \
            "$WATCHTOWER_BASE_URL/v1/update"
